#ifndef SVMDEFINES_H
#define SVMDEFINES_H

#define RANDOM_PATCH_COUNT 100
#define SVM_ITERATIONS 100000
#define SVM_OUTPUT_NAME "SVM_MARC.yaml"
#define WINDOW_SIZE 64
#define DESCRIPTOR_SIZE 1764
#define DOWNSCALE_FACTOR 0.8

#endif // SVMDEFINES_H