#ifndef SVMDEFINES_H
#define SVMDEFINES_H

#define RANDOM_PATCH_COUNT 200
#define SVM_ITERATIONS 100000
#define SVM_OUTPUT_NAME "SVM_MARC.yaml"
#define WINDOW_SIZE 64
#define DESCRIPTOR_SIZE 1764
// Standard = 0.8
#define DOWNSCALE_FACTOR 0.91
// Standard = 5
#define PATCH_PIXEL_MOVEMENT 23

#endif // SVMDEFINES_H